# ============================================================
#  NexOS — dnscrypt-proxy Configuration
#  /etc/dnscrypt-proxy/dnscrypt-proxy.toml
#  DNS-over-HTTPS for privacy
# ============================================================

listen_addresses = ['127.0.2.1:53']
max_clients = 250

# Use servers with DNSSEC, no logging, no filtering
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true

# Timeouts
timeout = 5000
keepalive = 30
lb_estimator = true
lb_strategy = 'p2'

# Cache
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

# Use multiple sources
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

# Anonymized DNS relay
[anonymized_dns]
skip_incompatible = true
